apiVersion: 1

datasources:
  - name: Transport DB
    uid: transport-db
    type: grafana-postgresql-datasource
    url: postgres:5432
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      database: transport
      sslmode: disable
      postgresVersion: 1700
    isDefault: true
