[project]
name = "transceiver"
version = "0.1.0"
description = "Приём телематики NDTP по TCP и отправка пакетов в инференс"
requires-python = ">=3.14"
dependencies = [
    "aiokafka>=0.14.0",
    "fastapi>=0.141.1",
    "pydantic-settings>=2.15.0",
    "uvicorn[standard]>=0.54.0",
]

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
